### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by Diabe1337** [Friendly-Technologies/Friendly-LwM2M-Client#13]
When I try to run the build command I get an error. Although it does not say which error unfortunately.

![image](https://github.com/user-attachments/assets/bd39a58b-a441-4b9c-8fa4-c813fb1bf3d0)

I setup ubuntu on a virtual machine. Then went through all the steps as described in the readme.

**Comment by VSkoshchuk** [comment]
Hello!

Regarding the logs you sent, they indicate that the issue occurs when trying to build **libcoap**. This could be related to four things:
1. Missing repository: Please ensure that the **libcoap** repository is present at the following path: "Friendly-LwM2M-Client/examples/coap/libcoap".
2. Problems during the build process of the **libcoap** repository: If the repository is present, then detailed logs describing the compilation process and any issues will be stored in the file "Friendly-LwM2M-Client/examples/coap/libcoap/build.build.log".
3. Incorrect Ubuntu version: The OS should be Ubuntu 22.04.
4. Incorrect execution of the **wpp_env_setup.sh** script, which sets up the environment.

Please provide the results of checking the steps I've described so that we can identify the problem.

Best regards

**Comment by Diabe1337** [comment]
Indeed using the wrong ubuntu version. I will reinstall the correct version and come back with the results

**Comment by Diabe1337** [comment]
Turns out it was not necessarily due to the Ubuntu version but more the git clone command.

As you do the git clone command there is a lot of permission denied errors on the submodules.
To solve this I went over every error and cloned those separately into the folder. A lot of work but it seems to work. 

![image](https://github.com/user-attachments/assets/023f852f-9f17-4f6d-b60a-c6735a350baf)
Now checking if the build process works alright.  

update: Getting an 'unused function' error on building
I think its due to mismatching versions of the submodules due to manual pulling.

Update: Yep, downloaded all the correct version as zip and extracted them in the right spot. The build process is completing now. So in the end all of the errors are due to the git pulling process.

**Comment by Diabe1337** [comment]
Getting an 'unused function' error on building 
![image](https://github.com/user-attachments/assets/8a9749a4-c122-415b-bd27-7ca96dfafd9e)

**Comment by Diabe1337** [comment]
My guess that its due to wrong versions of the submodules maybe. As I had to manually pull them

**Comment by VSkoshchuk** [comment]
The error message you're encountering indicates that the Git submodules are not being cloned due to permission issues related to SSH keys. The primary issue is the Permission denied (publickey) error, which suggests that your SSH key is either not set up correctly, not added to the SSH agent, or not linked to your GitHub account.

1. Ensure you have an SSH key generated. You can check by looking for id_rsa and id_rsa.pub in your ~/.ssh/ directory.
2. Add SSH Key to GitHub: Go to GitHub -> Settings -> SSH and GPG keys -> New SSH key -> Paste the key.
3. Try to clone the repo again: git clone --recurse-submodules git@github.com:Friendly-Technologies/Friendly-LwM2M-Client.git
